### ISSUE TITLE
Update base action does not account for the experimental label

### ISSUE THREAD

**Issue by haykam821** [FabricMC/fabric-action-scripts#4]
When modifying labels for a pull request that has had its base updated, the experimental label is not added or removed.

**Comment by modmuss50** [comment]
Not quite sure what you mean by this? I dont see what the experimental label has to do with this?

**Comment by haykam821** [comment]
Updating a pull request's base branch typically changes the version label (`release` or `snapshot`) to match the new branch. However, this is not done for experimental versions.
