### ISSUE TITLE
Close support issues as not planned

### ISSUE THREAD

**Issue by haykam821** [FabricMC/fabric-action-scripts#7]
Although the [GitHub REST API](https://docs.github.com/en/rest/issues/issues#update-an-issue) does not document any way of differentiating closed issues between completed and not planned, it seems that a `state_reason` value of `not_planned` would allow the workflow to close the issue as not planned:

```sh
gh api -X PATCH repos/FabricMC/fabric-action-scripts/issues/7 -f state='closed' -f state_reason='not_planned'
```

**Comment by modmuss50** [comment]
Seems it should be that easy 👍
